apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: trident-csi-nas
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  fsType: "ext4"
allowVolumeExpansion: True