fluentbit:
  enable: true
  input:
    tail:
      enable: true
      path: "/var/log/*/*/*.log"
  output:
    stdout: 
      enable: true
  filter:
    kubernetes:
      enable: false
      labels: true
      annotations: true
    containerd:
      enable: false
    systemd:
      enable: false
      
  additionalVolumes: 
    - name: shared-logs
      persistentVolumeClaim:
        claimName: shared-pv
  additionalVolumesMounts: 
    - name: shared-logs
      mountPath: /var/log
      readOnly: false
      # subPathExpr: $(NODE_NAME)
