apiVersion: v1
kind: Namespace
metadata:
  name: ns2
---
apiVersion: trident.netapp.io/v1
kind: TridentVolumeReference
metadata:
  name: ns-app-pvc
  namespace: ns2
spec:
  pvcName: shared-pv
  pvcNamespace: fluent
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
      trident.netapp.io/shareFromPVC: fluent/shared-pv
  name: ns2-app-pvc
  namespace: ns2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: trident-csi-nas
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-writer-ns2
  namespace: ns2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: time-writer-ns2
  template:
    metadata:
      labels:
        app: time-writer-ns2
    spec:
      containers:
      - name: time-writer-ns2
        image: alpine:latest
        command: ["/bin/sh"]
        args:
        - "-c"
        - >
          mkdir -p /var/log/$(NODE_NAME)/$(POD_NAME);
          while true; do
            date >> /var/log/$(NODE_NAME)/$(POD_NAME)/time.log;
            sleep 20;
          done
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: logs
          mountPath: /var/log
          # subPathExpr: $(NODE_NAME)/$(POD_NAME)

      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: ns2-app-pvc

# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: time-writer-ns2-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: trident-csi-nas